version: "3.8"

services:
  backend:
    container_name: roman_converter_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production
    restart: always
    depends_on:
      - frontend

  frontend:
    container_name: roman_converter_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=production
    restart: always
